### ISSUE TITLE
Support for "LDAP Signing" and "Channel Binding"?

### ISSUE THREAD

**Issue by corsch** [p0dalirius/LDAPmonitor#5]
This is a great tool, but unfortunately is is not working if the DC enforces "LDAP Signing" and "Channel Binding".

`[+]======================================================
[+]    LDAP live monitor v1.1        @podalirius_
[+]======================================================

[>] Trying to connect to <DC IP> ...
Traceback (most recent call last):
  File "<PATH>/tools/LDAPmonitor/python/pyLDAPmonitor.py", line 513, in <module>
    raise e
  File "<PATH>/tools/LDAPmonitor/python/pyLDAPmonitor.py", line 478, in <module>
    ldap_server, ldap_session = init_ldap_session(
  File "<PATH>/tools/LDAPmonitor/python/pyLDAPmonitor.py", line 213, in init_ldap_session
    return init_ldap_connection(target, None, args, domain, username, password, lmhash, nthash)
  File "<PATH>/tools/LDAPmonitor/python/pyLDAPmonitor.py", line 193, in init_ldap_connection
    ldap_session = ldap3.Connection(ldap_server, user=user, password=password, authentication=ldap3.NTLM, auto_bind=True)
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 363, in __init__
    self._do_auto_bind()
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 412, in _do_auto_bind
    raise LDAPBindError(error)
ldap3.core.exceptions.LDAPBindError: automatic bind not successful - strongerAuthRequired`

**Comment by p0dalirius** [comment]
In order to solve this problem, I recreated a test environment:

## Test environment

Setting registry keys in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NTDS\Parameters` to the following values:

 - `LDAPServerIntegrity` : **2** (Require Signing)
 - `LdapEnforceChannelBinding` : **2** (Always)

Source: https://support.microsoft.com/en-us/topic/2020-ldap-channel-binding-and-ldap-signing-requirements-for-windows-ef185fb8-00f7-167d-744c-f299a66fc00a

## Bug

```
./ldapmonitor.py -d LAB.local -u Administrator -p 'Admin123!' --dc-ip 192.168.2.1
[+]======================================================
[+]    LDAP live monitor v1.3        @podalirius_        
[+]======================================================

[>] Trying to connect to 192.168.2.1 ...
Traceback (most recent call last):
  File "/data/./ldapmonitor.py", line 532, in <module>
    raise e
  File "/data/./ldapmonitor.py", line 501, in <module>
    ldap_server, ldap_session = init_ldap_session(
  File "/data/./ldapmonitor.py", line 217, in init_ldap_session
    return init_ldap_connection(target, None, args, domain, username, password, lmhash, nthash)
  File "/data/./ldapmonitor.py", line 197, in init_ldap_connection
    ldap_session = ldap3.Connection(ldap_server, user=user, password=password, authentication=ldap3.NTLM, auto_bind=True)
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 356, in __init__
    self._do_auto_bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 405, in _do_auto_bind
    raise LDAPBindError(error)
[trace.pcapng.zip](https://github.com/p0dalirius/LDAPmonitor/files/7810613/trace.pcapng.zip)

ldap3.core.exceptions.LDAPBindError: automatic bind not successful - strongerAuthRequired
```

## Wireshark trace

During this bug, a Wireshark capture of the traffic was made from the domain controller:

![image](https://user-images.githubusercontent.com/79218792/148128534-ca12f76b-7486-4656-99bd-da4e40bca176.png)

 - **Capture file**: [trace.pcapng.zip](https://github.com/p0dalirius/LDAPmonitor/files/7810615/trace.pcapng.zip)

**Comment by p0dalirius** [comment]
The problem seems to come from the required LDAP signing (in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NTDS\Parameters`):

| Property                      | Value                             | LDAPmonitor can connect? |
|-------------------------------|--------------------------------|-------------|
| `LDAPServerIntegrity` | **1** (None)                  | Yes :heavy_check_mark: |
| `LDAPServerIntegrity` | **2** (Require Signing) | Nope :x: |

![image](https://user-images.githubusercontent.com/79218792/148131397-9e08464e-7cfa-40ad-a7d4-cda07c07d51c.png)

And LDAPmonitor works fine with `LDAPServerIntegrity` set to **1** (None) which does not require signing:

![image](https://user-images.githubusercontent.com/79218792/148131953-a13e57f5-87ce-4d1b-93ad-0b81ff8b12cb.png)

**Comment by LightxR** [comment]
This issue could be solved by using ldap3 dev branch (nice PR for ldap signing and channel binding) or waiting the merge on the main branch.
I tested it out by modifying sectools librairy, see : https://github.com/p0dalirius/sectools/pull/10
